### PR TITLE
add num_docs

### PR DESCRIPTION
**Pull request by 0x376h**
add num_docs

**Goals:**

- get num_docs ，fix some mistakes in use
- [ ] check and update documentation. See [guide](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md#-contributing-documentation) and ask the team.

### CODE REVIEW

**Review by JoanFM — CHANGES_REQUESTED** [review]
can you add a small test for this?

**Comment by 0x376h** [comment]
code like this:

from docarray import DocList
import numpy as np
from vectordb import InMemoryExactNNVectorDB, HNSWVectorDB
from docarray import BaseDoc
from docarray.typing import NdArray

class ToyDoc(BaseDoc):
  text: str = ''
  embedding: NdArray[128]

# Specify your workspace path
db = InMemoryExactNNVectorDB[ToyDoc](workspace='./workspace_path')

# Index a list of documents with random embeddings
doc_list = [ToyDoc(text=f'toy doc {i}', embedding=np.random.rand(128)) for i in range(1000)]
db.index(inputs=DocList[ToyDoc](doc_list))
print(db.num_docs())

**Comment by JoanFM** [comment]
> code like this: ` from docarray import DocList import numpy as np from vectordb import InMemoryExactNNVectorDB, HNSWVectorDB from docarray import BaseDoc from docarray.typing import NdArray
> 
> class ToyDoc(BaseDoc): text: str = '' embedding: NdArray[128]
> 
> db = InMemoryExactNNVectorDB[ToyDoc](workspace='./workspace_path')
> 
> doc_list = [ToyDoc(text=f'toy doc {i}', embedding=np.random.rand(128)) for i in range(1000)] db.index(inputs=DocList[ToyDoc](doc_list))
> 
> print(db.num_docs())`

A test for each case, not a print, somewhere where you assert it tells the right number

**Comment by 0x376h** [comment]
test case like this?
```python
from docarray import DocList
import numpy as np
from vectordb import InMemoryExactNNVectorDB, HNSWVectorDB
from docarray import BaseDoc
from docarray.typing import NdArray

class ToyDoc(BaseDoc):
  str = ''
  embedding: NdArray[128]

def test_inmemory_num_dos(tmpdir):
  db = InMemoryExactNNVectorDB[ToyDoc](workspace=str(tmpdir))
  doc_list = [ToyDoc(text=f'toy doc {i}', embedding=np.random.rand(128)) for i in range(1000)]
  db.index(inputs=DocList[ToyDoc](doc_list))
  x=db.num_docs()
  assert x['num_docs']==1000

def test_hnsw_num_dos(tmpdir):
  db = HNSWVectorDB[ToyDoc](workspace=str(tmpdir))
  doc_list = [ToyDoc(text=f'toy doc {i}', embedding=np.random.rand(128)) for i in range(1000)]
  db.index(inputs=DocList[ToyDoc](doc_list))
  x=db.num_docs()
  assert x['num_docs']==1000
```

**Comment by JoanFM** [comment]
Thanks for the contribution @0x376h

**Pull request merged**
